
export const sample_foods: any[] = [
    {
        id: '1',
        name: 'Pizza Pepperoni',
        cookTime: '10-20',
        price: 200,
        favorite: false,
        origins: ['italy'],
        stars: 4.5,
        imageUrl: 'https://raw.githubusercontent.com/nasirjd/foodmine-course/007095da4fef5c43d1f2f309c4a85b42677405ad/frontend/src/assets/food-1.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '2',
        name: 'Meatball',
        price: 200,
        cookTime: '20-30',
        favorite: true,
        origins: ['persia', 'middle east', 'china'],
        stars: 4.7,
        imageUrl: 'https://raw.githubusercontent.com/nasirjd/foodmine-course/007095da4fef5c43d1f2f309c4a85b42677405ad/frontend/src/assets/food-2.jpg',
        tags: ['SlowFood', 'Lunch'],
    },
    {
        id: '3',
        name: 'Hamburger',
        price: 400,
        cookTime: '10-15',
        favorite: false,
        origins: ['germany', 'us'],
        stars: 3.5,
        imageUrl: 'https://raw.githubusercontent.com/nasirjd/foodmine-course/007095da4fef5c43d1f2f309c4a85b42677405ad/frontend/src/assets/food-3.jpg',
        tags: ['FastFood', 'Hamburger'],
    },
    {
        id: '4',
        name: 'Fried Potatoes',
        price: 150,
        cookTime: '15-20',
        favorite: true,
        origins: ['belgium', 'france'],
        stars: 3.3,
        imageUrl: 'https://raw.githubusercontent.com/nasirjd/foodmine-course/007095da4fef5c43d1f2f309c4a85b42677405ad/frontend/src/assets/food-4.jpg',
        tags: ['FastFood', 'Fry'],
    },
    {
        id: '5',
        name: 'Chicken Soup',
        price: 200,
        cookTime: '40-50',
        favorite: false,
        origins: ['india', 'asia'],
        stars: 3.0,
        imageUrl: 'https://raw.githubusercontent.com/nasirjd/foodmine-course/007095da4fef5c43d1f2f309c4a85b42677405ad/frontend/src/assets/food-5.jpg',
        tags: ['SlowFood', 'Soup'],
    },
    {
        id: '6',
        name: 'Vegetables Pizza',
        price: 300,
        cookTime: '40-50',
        favorite: false,
        origins: ['italy'],
        stars: 4.0,
        imageUrl: 'https://raw.githubusercontent.com/nasirjd/foodmine-course/007095da4fef5c43d1f2f309c4a85b42677405ad/frontend/src/assets/food-6.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '7',
        name: 'Chicken Pizza',
        price: 400,
        cookTime: '50-60',
        favorite: true,
        origins: ['china'],
        stars: 4.9,
        imageUrl: 'https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/216054.jpg?resize=1200:*',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '8',
        name: 'Gobi Manchurian',
        price: 150,
        cookTime: '10-15',
        favorite: false,
        origins: ['india'],
        stars: 4.3,
        imageUrl: 'https://theyummydelights.com/wp-content/uploads/2020/02/gobi-manchurian-8.jpg',
        tags: ['FastFood', 'Lunch', 'Fry'],
    },
    {
        id: '9',
        name: 'Chicken Shawarma',
        price: 100,
        cookTime: '10-20',
        favorite: true,
        origins: ['india'],
        stars: 4.9,
        imageUrl: 'https://www.thechunkychef.com/wp-content/uploads/2021/03/Chicken-Shawarma-recipe-card.jpg',
        tags: ['FastFood', 'Fry'],
    }
]

export const sample_tags:any[] = [
    { name: 'All', count: 9 },
    { name: 'FastFood', count: 7 },
    { name: 'Pizza', count: 3 },
    { name: 'Lunch', count: 5 },
    { name: 'SlowFood', count: 2 },
    { name: 'Hamburger', count: 1 },
    { name: 'Fry', count: 3 },
    { name: 'Soup', count: 1 },
]

export const sample_users:any[] = [
    {
        name: 'Subash',
        email: 'subashinr.is@gmail.com',
        password: 'sub@123',
        address: '3, new police quarters, reserve line, sivakasi',
        isAdmin: true
    },
    {
        name: 'Anand',
        email: 'anand@gmail.com',
        password: 'anand@123',
        address: '4, new police quarters, reserve line, sivakasi',
        isAdmin: true
    },
    {
        name: 'Kathir',
        email: 'kathir@gmail.com',
        password: 'kathir@123',
        address: '5, new police quarters, reserve line, sivakasi',
        isAdmin: true
    }
]